### ISSUE TITLE
Log relevant information in JSON format

### ISSUE THREAD

**Issue by palmerabollo** [Telefonica/node-express-logging#3]
Current logs have this format:

```
Response with status 304 in 5 ms
```

They are not as useful as they should for a machine. What do you thing about logging them as:

```
Response {"statusCode": 304, "duration": 5}
```

I think we just need to change:

``` js
 logger.info('Response with status %d in %d ms.', res.statusCode, duration);
```

to:

``` js
 logger.info('Response', {statusCode: res.statusCode, duration: duration});
```

and would work for both [logops](https://github.com/telefonicaid/logops) and no-logops users

**Comment by jlorgal** [comment]
It would be nice to have this feature but there are several problems:
 - If logger is console.log, then
